config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    authenticated :user do
      root to: "devices#index", as: :authenticated_root
    end
  end

  # Admin routes
  scope "/admin" do
    resources :users
    resources :incoming_messages do
      collection do
        delete :destroy_all
      end
    end
  end

  # Public routes
  namespace :public do
    resources :devices, only: :show do
      resources :average_hourly_measurements, only: :index
      resources :average_daily_measurements, only: :index
      resources :measurements, only: [:index, :show]
    end
  end

  # Static pages
  get "/contact", to: "contacts#new"
  get "/hoe", to: "pages#how"
  get "/richtlijnen", to: "pages#guidelines"
  get "/metingen", to: "pages#measurements"
  get "/over-ons", to: "pages#about"

  # Contact form
  resources :contacts, only: [:new, :create]

  # Other resources
  resources :devices do
    resources :average_hourly_measurements
    resources :average_daily_measurements
    resources :measurements do
      collection do
        delete :destroy_all
      end
    end
    member do
      put :regenerate_api_key
      delete :destroy_photo
      get :dust_level
      get :loss
    end
  end
  resources :losses

  root to: redirect("/users/sign_in")
end

app/models/incoming_message.rb
class IncomingMessage < ActiveRecord::Base
  def device_eui
    if proximus?
      self.body['DevEUI_uplink']['DevAddr']
    else
      self.body['devAddr']
    end
  end

  def gateway_eui
    if lora?
      if proximus?
        'Proximus LoRa network'
      else
        self.body['gatewayEui']
      end
    else
      "WiFi"
    end
  end

  def frequency
    self.body['frequency'] unless proximus?
  end

  def rssi
    if proximus?
      self.body['DevEUI_uplink']['LrrRSSI']
    else
      self.body['rssi']
    end
  end

  def snr
    if proximus?
      self.body['DevEUI_uplink']['LrrSNR']
    else
      self.body['snr']
    end
  end

  def data
    if wifi?
      self.body["measurement"]
    else
      if proximus?
        self.body['DevEUI_uplink']['payload_hex']
      else
        begin
          Base64.decode64(self.body['payload']).unpack("H*").first
        rescue
          ""
        end
      end
    end
  end

  def proximus?
    self.body.key?("DevEUI_uplink")
  end

  def wifi?
    self.body["transport"] == "wifi"
  end

  def lora?
    !wifi?
  end
end

app/controllers/incoming_messages_controller.rb
class IncomingMessagesController < ApplicationController
  before_action :require_admin
  before_action :set_incoming_message, only: [:show, :destroy]
  add_breadcrumb :index, :incoming_messages_path
  respond_to :html

  def index
    @q = IncomingMessage.search(params[:q])
    @q.sorts = "timestamp desc" if @q.sorts.empty?
    @incoming_messages = @q.result.page(params[:page])
  end

  def show
    add_breadcrumb @incoming_message.id.to_s
    respond_with(@incoming_message)
  end

  def destroy
    @incoming_message.destroy
    respond_with(@incoming_message)
  end

  def destroy_all
    IncomingMessage.destroy_all
    redirect_to :incoming_messages, notice: "Destroyed all incoming messages."
  end

  private

  def set_incoming_message
    @incoming_message = IncomingMessage.find(params[:id])
  end
end

app/views/incoming_messages/index.html.haml
- model_class = IncomingMessage

.page-header
  %h1 Incoming messages

.row
  .col-md-4
    = link_to icon_text("trash", "Delete all"), [:destroy_all, :incoming_messages], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger"
    = link_to icon_text("refresh", "Refresh"), "#", class: "btn btn-sm btn-default", id: "refresh-link"
  .col-md-1
    &nbsp;
  .col-md-7
    = search_form_for @q do |f|
      .row
        .col-sm-3
          = f.input :identifier_eq, as: :select, collection: identifiers.prepend(""), include_blank: false, input_html: { class: "input-sm" }, required: false, label: "Filter device:"

.row
  .col-lg-12
    .text-right= page_entries_info @incoming_messages
    .text-center= paginate @incoming_messages, theme: "twitter-bootstrap-3"

    %table.table.table-striped.table-condensed#incoming_messages
      %thead
        %tr
          %th= sort_link(@q, :timestamp, default_order: :desc)
          %th= model_class.human_attribute_name(:gateway_eui)
          %th= model_class.human_attribute_name(:identifier)
          %th= model_class.human_attribute_name(:frequency)
          %th= model_class.human_attribute_name(:rssi)
          %th= model_class.human_attribute_name(:snr)
          %th Payload
      %tbody
        - @incoming_messages.each do |incoming_message|
          %tr{ id: dom_id(incoming_message) }
            %td= link_to incoming_message.timestamp, incoming_message_path(incoming_message)
            %td= incoming_message.gateway_eui
            %td= incoming_message.identifier
            %td
              - if incoming_message.frequency.present?
                = incoming_message.frequency
                MHz
            %td= incoming_message.rssi
            %td= incoming_message.snr
            %td= incoming_message.data

    .text-center= paginate @incoming_messages, theme: "twitter-bootstrap-3"

app/views/incoming_messages/show.html.haml
- model_class = IncomingMessage

.page-header
  %h1
    = @incoming_message.id
    %small= t '.title', default: model_class.model_name.human.titleize

.row
  .col-lg-3
    .row
      .col-sm-4.col-lg-12
        .well
          = link_to icon_text("trash-o", t('.destroy', default: t("helpers.links.destroy"))), incoming_message_path(@incoming_message), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger btn-block'

  .col-lg-9
    .row
      .col-md-6
        %p
          %strong= model_class.human_attribute_name(:timestamp)
          %br
          = @incoming_message.timestamp

        %p
          %strong= model_class.human_attribute_name(:gateway_eui)
          %br
          = @incoming_message.gateway_eui

        %p
          %strong= model_class.human_attribute_name(:device_eui)
          %br
          = @incoming_message.device_eui

      .col-md-6
        %p
          %strong= model_class.human_attribute_name(:frequency)
          %br
          - if @incoming_message.frequency.present?
            = @incoming_message.frequency
            MHz

        - %w(rssi snr data).each do |attr|
          %p
            %strong= model_class.human_attribute_name(attr)
            %br
            = @incoming_message.send(attr)

    %p
      %strong= model_class.human_attribute_name(:body)
      %br
      = @incoming_message.body