config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    authenticated :user do
      root to: "devices#index", as: :authenticated_root
    end
  end

  # Admin routes
  scope "/admin" do
    resources :users
    resources :incoming_messages do
      collection do
        delete :destroy_all
      end
    end
  end

  # Public routes
  namespace :public do
    resources :devices, only: :show do
      resources :average_hourly_measurements, only: :index
      resources :average_daily_measurements, only: :index
      resources :measurements, only: [:index, :show]
    end
  end

  # Static pages
  get "/contact", to: "contacts#new"
  get "/hoe", to: "pages#how"
  get "/richtlijnen", to: "pages#guidelines"
  get "/metingen", to: "pages#measurements"
  get "/over-ons", to: "pages#about"

  # Contact form
  resources :contacts, only: [:new, :create]

  # Other resources
  resources :devices do
    resources :average_hourly_measurements
    resources :average_daily_measurements
    resources :measurements do
      collection do
        delete :destroy_all
      end
    end
    member do
      put :regenerate_api_key
      delete :destroy_photo
      get :dust_level
      get :loss
    end
  end
  resources :losses

  root to: redirect("/users/sign_in")
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_attached_file :photo,
    styles: { thumb: "x200>" },
    path: ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
    url: "/system/:class/:attachment/:id/:style/:filename"
  validates_attachment_content_type :photo, content_type: ["image/jpeg", "image/gif", "image/png"]

  validates :name, presence: true
  validates :transport, presence: true
  validates :device_eui, uniqueness: true, allow_blank: true

  belongs_to :user
  has_many :measurements, dependent: :destroy
  has_many :average_hourly_measurements
  has_many :average_daily_measurements

  before_create :generate_api_key

  def name_with_id
    "#{name} (#{id})"
  end

  def generate_api_key
    self.api_key = loop do
      random_api_key = SecureRandom.urlsafe_base64(nil, false)
      break random_api_key unless Device.exists?(api_key: random_api_key)
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show,
    :edit, :update, :destroy, :regenerate_api_key,
    :dust_level, :destroy_photo]
  before_action :set_common_breadcrumbs, only: [:show, :new, :edit]
  respond_to :html

  def index
    @q = current_user.devices.search(params[:q])
    @q.sorts = "name ASC" if @q.sorts.empty?
    @devices = @q.result(distinct: true).page(params[:page])
    respond_with(@devices)
  end

  def show
    add_breadcrumb @device.name
    @measurements = @device.measurements.where(is_valid: true).order(timestamp: :desc).limit(4000).reverse
    respond_with(@measurements)
  end

  def new
    add_breadcrumb :new
    @device = current_user.devices.new
    respond_with(@device)
  end

  def edit
    add_breadcrumb @device.name, @device
    add_breadcrumb :edit
  end

  def create
    @device = current_user.devices.new(device_params)
    if @device.save
      redirect_to @device
    else
      set_common_breadcrumbs
      add_breadcrumb :new
      render :new
    end
  end

  def update
    if @device.update(device_params)
      redirect_to [:edit, @device], notice: "Wijzigingen met succes bewaard."
    else
      set_common_breadcrumbs
      add_breadcrumb @device.name, @device
      add_breadcrumb :edit
      render :edit
    end
  end

  def regenerate_api_key
    @device.generate_api_key
    @device.save
    redirect_to [:edit, @device], notice: "API key met succes vernieuwd. Vergeet je code niet aan te passen!"
  end

  def destroy_photo
    @device.photo = nil
    @device.save
    redirect_to [:edit, @device], notice: "Foto met succes verwijderd."
  end

  def destroy
    if @device.measurements.any?
      redirect_to @device, alert: t("flash.devices.has_measurements")
    else
      @device.destroy
      redirect_to :devices
    end
  end

  def dust_level
    render layout: false
  end

  def loss

  end

  private

  def device_params
    params.
      require(:device).
      permit(:name,
             :location,
             :transport,
             :device_eui,
             :public,
             :photo
      )
  end

  def set_device
    @device = current_user.devices.find(params[:id])
  end

  def set_common_breadcrumbs
    add_breadcrumb t("devices.index.title"), :devices
  end
end

app/views/devices/_device.html.haml
.col-sm-6.col-md-4.col-lg-3
  .thumbnail
    - if device.photo.present?
      = link_to image_tag(device.photo.url(:thumb)), device
    - else
      = link_to device, class: "no-hover" do
        .text-center
          %p{style: "font-size: 5em;"}= icon_text("dashboard")

    .row
      .col-lg-12
        &nbsp;
    .row
      .col-lg-12
        %h3.truncate= device.name
    .row
      .col-lg-12
        Fijnstofniveau
        = dust_level_badge(device)
    .row
      .col-lg-12
        - if device.location.present?
          = icon_text("map-marker")
          %em= device.location
        - else
          &nbsp;

app/views/devices/_header.html.haml
.page-header
  .row
    .col-sm-8
      %h1
        = @device.name
        %small= @device.location
    .col-sm-4
      .text-right
        = link_to icon_text("pencil", "Meter bewerken"), [:edit, @device], class: "btn btn-warning"

%ul.nav.nav-pills.nav-justified
  %li{ role: "presentation", class: active?("devices") }= link_to icon_text("line-chart", "Detailgrafiek"), @device
  %li{ role: "presentation", class: active?("average_hourly_measurements") }
    = link_to icon_text("line-chart", "Uurgemiddelde"), [@device, :average_hourly_measurements]
  %li{ role: "presentation", class: active?("average_daily_measurements") }
    = link_to icon_text("line-chart", "Daggemiddelde"), [@device, :average_daily_measurements]
  %li{ role: "presentation", class: active?("measurements") }= link_to icon_text("list", "Alle metingen"), [@device, :measurements]

.row
  .col-lg-12
    &nbsp;

app/views/devices/chart.html.haml
- content_for(:title) do
  Mijn metingen
  &ndash;
  Detailgrafiek

- content_for :scripts do
  :javascript
    $(function () {
      var options1 = {
          chart: {
            zoomType: 'x',
            renderTo: 'container1',
            events: {
              load: function (e) {
                if (typeof(Storage) !== "undefined") {
                  // Reload series visibility from localstorage
                  var chart = e.target;
                  var series = chart.series;
                  var series_length = series.length;
                  for (var i = 0; i < series_length; i++) {
                    var series_visible = localStorage.getItem("daily_series_" + i + "_visible");
                    if (series_visible == "hidden") {
                      series[i].setVisible(false);
                    } else {
                      series[i].setVisible(true);
                    }
                  }
                }
              }
            }
          },
          title: {
            text: 'PM 10 en PM 2.5 ratio'
          },
          subtitle: {
              text: document.ontouchstart === undefined ?
                      'Klik en sleep in de grafiek om in te zoomen' : 'Knijp de grafiek om in te zoomen'
          },
          plotOptions: {
            series: {
              events: {
                legendItemClick: function (e) {
                  if (typeof(Storage) !== "undefined") {
                    var series = e.target;
                    if (series.visible) {
                      localStorage.setItem("daily_series_" + series.index + "_visible", "hidden");
                    } else {
                      localStorage.removeItem("daily_series_" + series.index + "_visible");
                    }
                  }
                }
              }
            }
          },
          xAxis: {
            type: 'datetime',
            title: {
              text: 'Tijdstip'
            },
            dateTimeLabelFormats: {
              day: '%a %e %b'
            },
            crosshair: true
          },
          yAxis: {
            labels: {
              format: '{value} %',
              style: {
                  color: Highcharts.getOptions().colors[1]
              }
            },
            title: {
                text: 'Ratio'
            }
          },
          tooltip: {
            shared: true,
            valueDecimals: 2,
            dateTimeLabelFormats: {
              millisecond: "%A, %b %e, %H:%M:%S.%L",
              second: "%A, %b %e, %H:%M:%S",
              minute: "%A, %b %e, %H:%M",
              hour: "%A %e %b %H:%M",
              day: "%A, %b %e, %Y",
              week: "Week van %A, %b %e, %Y",
              month: "%B %Y",
              year: "%Y"
            }
          },
          legend: {
            enabled: true,
            borderWidth: 1,
            align: 'center',
          },
          series: [{
            name: 'PM 10',
            type: 'line',
            data: #{@measurements.map{|m| [m.chart_datetime, m.p2_ratio]}},
            tooltip: {
              valueSuffix: ' %'
            }
          },
          {
            name: 'PM 2.5',
            type: 'line',
            data: #{@measurements.map{|m| [m.chart_datetime, m.pm25_ratio]}},
            tooltip: {
              valueSuffix: ' %'
            }
          }]
      };

      var chart1 = new Highcharts.Chart(options1);
    });

.page-header
  %h1
    Mijn metingen
    %small Detailgrafiek

.row
  .col-lg-12
    #container1{style: "min-width: 310px; height: 500px; margin: 0 auto"}

app/views/devices/dust_level.html.haml
!!! 5
%html(lang="#{I18n.locale}")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta{"http-equiv" => "refresh", "content" => "60"}
    %title
      = t("app_name")
      &ndash;
      = @device.name
      - if @device.location.present?
        &ndash;
        = @device.location

  %body{style: "background-color: #{dust_level_color(@device)}"}

app/views/devices/edit.html.haml
- model_class = Device

.page-header
  %h1
    = @device.name
    %small=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize

= simple_form_for @device do |f|
  .row
    .col-md-4
      = f.input :name
      = f.input :transport, collection: TRANSPORTS
      = f.input :device_eui, hint: "Alleen nodig voor LoRa. Maak leeg voor WiFi."
      .form-group
        %label.control-label API key
        %br
        .well= @device.api_key

      .form-group
        = link_to icon_text("refresh", "API key vernieuwen"), [:regenerate_api_key, @device], method: :put, data: {confirm: "Deze actie maakt de vorige API key ongeldig. Ben je zeker?"}, class: "btn btn-info btn-sm"
    .col-md-4
      - if @device.photo.present?
        .thumbnail
          = image_tag @device.photo.url(:thumb)
          .text-right= link_to icon_text("trash-o"), [:destroy_photo, @device], method: "delete", class: "btn btn-danger btn-xs"
      = f.input :photo, as: :file
      = f.input :location
      .well
        = f.input :public, wrapper: :vertical_boolean, hint: "Wanneer je je meter publiek maakt kunnen anderen je metingen zien via onderstaande link:"
        = link_to public_device_url(@device), public_device_url(@device)
      .well
        = link_to icon_text("trash-o", "Meter verwijderen"), @device, method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: "Are you sure?")) }, class: "btn btn-danger"

  %hr
  = f.button :submit, class: 'btn-primary'
  = link_to t('.cancel', default: t("helpers.links.cancel")), @device, class: 'btn btn-default'

app/views/devices/index.html.haml
- content_for(:title) do
  = t(".title")

.page-header
  .row
    .col-sm-8
      %h1= t(".title")
    .col-sm-4
      .text-right
        = link_to icon_text("plus", "Meter toevoegen"), [:new, :device], class: "btn btn-info"

%p.text-right= page_entries_info @devices
.text-center= paginate @devices, theme: "twitter-bootstrap-3"

.row
  .col-lg-12
    - if @devices.any?
      = render @devices
    - else
      Geen meters.
      = link_to "Voeg er een toe.", [:new, :device]

.text-center= paginate @devices, theme: "twitter-bootstrap-3"

app/views/devices/new.html.haml
- model_class = Device

.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize

= simple_form_for @device do |f|
  .row
    .col-md-4
      = f.input :name
      = f.input :transport, collection: TRANSPORTS
      = f.input :device_eui, hint: "Alleen nodig voor LoRa. Maak leeg voor WiFi."
      = f.input :location
      = f.input :photo, as: :file

  %hr
  = f.button :submit, class: 'btn-primary'
  = link_to t('.cancel', default: t("helpers.links.cancel")), @device, class: 'btn btn-default'

app/views/devices/show.html.haml
- content_for :scripts do
  :javascript
    $(function () {
      var options1 = {
          chart: {
            zoomType: 'x',
            renderTo: 'container1',
            events: {
              load: function (e) {
                if (typeof(Storage) !== "undefined") {
                  // Reload series visibility from localstorage
                  var chart = e.target;
                  var series = chart.series;
                  var series_length = series.length;
                  for (var i = 0; i < series_length; i++) {
                    var series_visible = localStorage.getItem("detailed_series_" + i + "_visible");
                    if (series_visible == "hidden") {
                      series[i].setVisible(false);
                    } else {
                      series[i].setVisible(true);
                    }
                  }
                }
              }
            }
          },
          title: {
            text: 'PM 10 en PM 2.5 ratio'
          },
          subtitle: {
              text: document.ontouchstart === undefined ?
                      'Klik en sleep in de grafiek om in te zoomen' : 'Knijp de grafiek om in te zoomen'
          },
          plotOptions: {
            series: {
              events: {
                legendItemClick: function (e) {
                  if (typeof(Storage) !== "undefined") {
                    var series = e.target;
                    if (series.visible) {
                      localStorage.setItem("detailed_series_" + series.index + "_visible", "hidden");
                    } else {
                      localStorage.removeItem("detailed_series_" + series.index + "_visible");
                    }
                  }
                }
              }
            }
          },
          xAxis: {
            type: 'datetime',
            title: {
              text: 'Tijdstip'
            },
            dateTimeLabelFormats: {
              day: '%a %e %b'
            },
            crosshair: true
          },
          yAxis: {
            labels: {
              format: '{value} %',
              style: {
                  color: Highcharts.getOptions().colors[1]
              }
            },
            title: {
                text: 'Ratio'
            }
          },
          tooltip: {
            shared: true,
            valueDecimals: 2,
            dateTimeLabelFormats: {
              millisecond: "%A, %b %e, %H:%M:%S.%L",
              second: "%A, %b %e, %H:%M:%S",
              minute: "%A, %b %e, %H:%M",
              hour: "%A %e %b %H:%M",
              day: "%A, %b %e, %Y",
              week: "Week van %A, %b %e, %Y",
              month: "%B %Y",
              year: "%Y"
            }
          },
          legend: {
            enabled: true,
            borderWidth: 1,
            align: 'center',
          },
          series: [{
            name: 'PM 10',
            type: 'line',
            data: #{@measurements.map{|m| [m.chart_datetime, m.p2_ratio]}},
            tooltip: {
              valueSuffix: ' %'
            }
          },
          {
            name: 'PM 2.5',
            type: 'line',
            data: #{@measurements.map{|m| [m.chart_datetime, m.pm25_ratio]}},
            tooltip: {
              valueSuffix: ' %'
            }
          }]
      };

      var chart1 = new Highcharts.Chart(options1);
    });

= render "devices/header"

#container1{style: "min-width: 310px; height: 500px; margin: 0 auto"}