config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    authenticated :user do
      root to: "devices#index", as: :authenticated_root
    end
  end

  # Admin routes
  scope "/admin" do
    resources :users
    resources :incoming_messages do
      collection do
        delete :destroy_all
      end
    end
  end

  # Public routes
  namespace :public do
    resources :devices, only: :show do
      resources :average_hourly_measurements, only: :index
      resources :average_daily_measurements, only: :index
      resources :measurements, only: [:index, :show]
    end
  end

  # Static pages
  get "/contact", to: "contacts#new"
  get "/hoe", to: "pages#how"
  get "/richtlijnen", to: "pages#guidelines"
  get "/metingen", to: "pages#measurements"
  get "/over-ons", to: "pages#about"

  # Contact form
  resources :contacts, only: [:new, :create]

  # Other resources
  resources :devices do
    resources :average_hourly_measurements
    resources :average_daily_measurements
    resources :measurements do
      collection do
        delete :destroy_all
      end
    end
    member do
      put :regenerate_api_key
      delete :destroy_photo
      get :dust_level
      get :loss
    end
  end
  resources :losses

  root to: redirect("/users/sign_in")
end

app/models/user.rb
require "shared_accessor"

class User < ActiveRecord::Base
  include SharedAccessor::FullName

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :registerable,
         :rememberable, :trackable, :validatable, :confirmable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  has_many :devices, dependent: :destroy

  def remember_me
    true
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    edit_user_registration_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html
  add_breadcrumb :index, :users_path

  def index
    @q = User.search(params[:q])
    @q.sorts = "last_name asc" if @q.sorts.empty?
    @users = @q.result(distinct: true).page(params[:page])
    respond_with(@users)
  end

  def show
    add_breadcrumb @user.full_name
    respond_with(@user)
  end

  def new
    add_breadcrumb :new
    @user = User.new
    respond_with(@user)
  end

  def edit
    add_breadcrumb @user.full_name, @user
    add_breadcrumb :edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      add_breadcrumb :new
      render :new
    end
  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    if user_tries_to_update_own_admin_status
      redirect_to :users, alert: t("flash.users.cannot_change_own_admin_status")
    else
      if @user.update(user_params)
        redirect_to @user
      else
        add_breadcrumb @user.full_name, @user
        add_breadcrumb :edit
        render :edit
      end
    end
  end

  def destroy
    if user_tries_to_delete_own_account
      redirect_to :users, alert: t("flash.users.cannot_delete_own_account")
    else
      @user.destroy
      respond_with(@user)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.
      require(:user).
      permit(:first_name,
             :last_name,
             :email,
             :password,
             :admin)
  end

  def user_tries_to_delete_own_account
    @user == current_user
  end

  def user_tries_to_update_own_admin_status
    params[:user][:admin].present? && @user == current_user
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, wrapper: :vertical_form, html: { autocomplete: "off" } do |f|
  .row
    .col-md-3
      = f.input :first_name
      = f.input :last_name
      = f.input :email

    .col-md-3.col-md-offset-1
      - if @user.new_record?
        = f.input :password
      - else
        = f.input :password, hint: t("devise.new_password_hint"), label: t("devise.new_password")

      = f.hidden_field :admin
      -# - if @user == current_user
      -#   = f.input :admin, as: :select, hint: t("devise.admin_disabled_hint"), disabled: true, include_blank: false
      -# - else
      -#   = f.input :admin, as: :select, hint: t("devise.admin_hint"), include_blank: false

  %hr
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), :back, class: 'btn btn-default'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1
    = @user.full_name
    %small=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize

= render "form"

app/views/users/index.html.haml
- model_class = User

.row
  .col-lg-3
    .row
      .col-sm-4.col-lg-12
        .well
          = link_to icon_text("plus", t('.new', default: t("helpers.links.new"))), new_user_path, class: 'btn btn-info btn-block'

  .col-lg-9
    .text-right=page_entries_info @users
    .text-center= paginate @users, theme: "twitter-bootstrap-3"

    %table.table.table-striped#users
      %thead
        %tr
          %th= sort_link(@q, :last_name, model_class.human_attribute_name(:full_name))
          %th= sort_link(@q, :email)
          %th= sort_link(@q, :created_at, default_order: :desc)
          -# %th= sort_link(@q, :admin, default_order: :desc)
      %tbody
        - @users.each do |user|
          %tr{ id: dom_id(user) }
            %td
              = link_to user_path(user) do
                = user.full_name
                - if user == current_user
                  %small
                    %i== (#{t("devise.this_is_you")})
            %td= user.email
            %td=l user.created_at, format: :short
            -# %td= user.admin? ? t("simple_form.yes") : t("simple_form.no")

      .text-center= paginate @users, theme: "twitter-bootstrap-3"

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1
    = @user.full_name
    %small= t '.title', default: model_class.model_name.human.titleize

.row
  .col-lg-3
    .row
      .col-sm-4.col-lg-12
        .well
          = link_to icon_text("pencil", t('.edit', default: t("helpers.links.edit"))), edit_user_path(@user), class: 'btn btn-warning btn-block'
          = link_to icon_text("trash-o", t('.destroy', default: t("helpers.links.destroy"))), user_path(@user), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger btn-block'

  .col-lg-9
    %p
      %strong= model_class.human_attribute_name(:email)
      %br
      = mail_to @user.email

    -# %p
    -#   %strong= model_class.human_attribute_name(:admin)
    -#   %br
    -#   = @user.admin? ? t("simple_form.yes") : t("simple_form.no")