config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    authenticated :user do
      root to: "devices#index", as: :authenticated_root
    end
  end

  # Admin routes
  scope "/admin" do
    resources :users
    resources :incoming_messages do
      collection do
        delete :destroy_all
      end
    end
  end

  # Public routes
  namespace :public do
    resources :devices, only: :show do
      resources :average_hourly_measurements, only: :index
      resources :average_daily_measurements, only: :index
      resources :measurements, only: [:index, :show]
    end
  end

  # Static pages
  get "/contact", to: "contacts#new"
  get "/hoe", to: "pages#how"
  get "/richtlijnen", to: "pages#guidelines"
  get "/metingen", to: "pages#measurements"
  get "/over-ons", to: "pages#about"

  # Contact form
  resources :contacts, only: [:new, :create]

  # Other resources
  resources :devices do
    resources :average_hourly_measurements
    resources :average_daily_measurements
    resources :measurements do
      collection do
        delete :destroy_all
      end
    end
    member do
      put :regenerate_api_key
      delete :destroy_photo
      get :dust_level
      get :loss
    end
  end
  resources :losses

  root to: redirect("/users/sign_in")
end

app/views/shared/_navbar.html.haml
.navbar.navbar-inverse.navbar-static-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    - if user_signed_in?
      = link_to t("app_name"), root_url, class: "navbar-brand"
    - else
      = link_to t("app_name"), "https://dustproof.be", class: "navbar-brand"

    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav
          %li{ class: active?("devices") || active?("average_daily_measurements") || active?("average_hourly_measurements") || active?("measurements") }= link_to icon_text("dashboard", t("devices.index.title")), devices_path
          - if current_user.admin?
            %li.dropdown
              = link_to "#", class: "dropdown-toggle", "aria-expanded" => false, data: { toggle: "dropdown" }, role: "button" do
                = icon_text("gear", "Admin")
                %span.caret
              %ul.dropdown-menu{ role: "menu" }
                %li= link_to icon_text("envelope", "Incoming messages"), incoming_messages_path
                %li= link_to icon_text("line-chart", "Lost measurements"), losses_path
                %li= link_to icon_text("users", "Gebruikers"), users_path

      %ul.nav.navbar-nav.navbar-right
        %li{ class: controller_name == "contacts" ? "active" : nil }= link_to icon_text("bullhorn", "Contact"), "/contact"
        - if user_signed_in?
          %li.dropdown
            = link_to "#", class: "dropdown-toggle", "aria-expanded" => false, data: { toggle: "dropdown" }, role: "button" do
              = current_user.full_name
              %span.caret
            %ul.dropdown-menu{ role: "menu" }
              %li= link_to icon_text("gear", t("devise.account_settings")), edit_user_registration_path
              %li= link_to icon_text("sign-out", t("devise.sign_out")), destroy_user_session_path, method: :delete